version: "3.9"

services:
  api:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  migrations:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    command:
      - sh
      - -c
      - python /app/manage.py makemigrations && python /app/manage.py migrate && python /app/manage.py loaddata initial_data.json


  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5