# Generated by Django 5.0.2 on 2024-02-29 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='language_id',
            new_name='language',
        ),
    ]
